/*
 * manifest.c — AndroidManifest.xml generator for Casperix APK Builder
 */

#include "manifest.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#  include <direct.h>
#  define MKDIR(p) _mkdir(p)
#else
#  include <sys/stat.h>
#  define MKDIR(p) mkdir(p, 0755)
#endif

int manifest_write(const ApkBuildConfig* config, const char* output_path) {
    FILE* f = fopen(output_path, "w");
    if (!f) return -1;

    const char* pkg  = config->package_name;
    const char* name = config->app_name;
    const char* act  = config->main_activity[0]
                       ? config->main_activity : "MainActivity";
    int  min_sdk     = config->min_sdk    ? config->min_sdk    : 24;
    int  target_sdk  = config->target_sdk ? config->target_sdk : 34;
    int  ver_code    = config->version_code ? config->version_code : 1;
    const char* ver  = config->version_name[0] ? config->version_name : "1.0.0";
    int  debuggable  = config->debug_build ? 1 : 0;

    fprintf(f,
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
        "    package=\"%s\"\n"
        "    android:versionCode=\"%d\"\n"
        "    android:versionName=\"%s\">\n"
        "\n"
        "    <uses-sdk\n"
        "        android:minSdkVersion=\"%d\"\n"
        "        android:targetSdkVersion=\"%d\" />\n"
        "\n"
        "    <!-- OpenGL ES 2.0 required for Skia GPU rendering -->\n"
        "    <uses-feature android:glEsVersion=\"0x00020000\"\n"
        "        android:required=\"true\" />\n"
        "\n"
        "    <application\n"
        "        android:label=\"@string/app_name\"\n"
        "        android:icon=\"@drawable/ic_launcher\"\n"
        "        android:hasCode=\"false\"\n"
        "        android:debuggable=\"%s\"\n"
        "        android:allowBackup=\"true\"\n"
        "        android:hardwareAccelerated=\"true\">\n"
        "\n"
        "        <!--\n"
        "            NativeActivity hosts the Casperix runtime as a native .so.\n"
        "            android_main() is the entry point generated by the compiler.\n"
        "        -->\n"
        "        <activity\n"
        "            android:name=\"android.app.NativeActivity\"\n"
        "            android:label=\"%s\"\n"
        "            android:configChanges=\"orientation|keyboardHidden|screenSize\"\n"
        "            android:screenOrientation=\"portrait\"\n"
        "            android:theme=\"@android:style/Theme.DeviceDefault.NoActionBar\"\n"
        "            android:windowSoftInputMode=\"adjustResize\"\n"
        "            android:exported=\"true\">\n"
        "\n"
        "            <!-- Name of the shared library without 'lib' prefix and '.so' suffix -->\n"
        "            <meta-data\n"
        "                android:name=\"android.app.lib_name\"\n"
        "                android:value=\"%s\" />\n"
        "\n"
        "            <intent-filter>\n"
        "                <action android:name=\"android.intent.action.MAIN\" />\n"
        "                <category android:name=\"android.intent.category.LAUNCHER\" />\n"
        "            </intent-filter>\n"
        "        </activity>\n"
        "    </application>\n"
        "</manifest>\n",
        pkg,
        ver_code,
        ver,
        min_sdk,
        target_sdk,
        debuggable ? "true" : "false",
        name,         /* activity label     */
        act           /* lib_name meta-data */
    );

    fclose(f);
    return 0;
}

int manifest_write_strings(const ApkBuildConfig* config, const char* res_dir) {
    /* Create res/values/ directory */
    char values_dir[768];
    snprintf(values_dir, sizeof(values_dir), "%s/values", res_dir);
    MKDIR(values_dir);

    char path[1024];
    snprintf(path, sizeof(path), "%s/strings.xml", values_dir);

    FILE* f = fopen(path, "w");
    if (!f) return -1;

    fprintf(f,
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<resources>\n"
        "    <string name=\"app_name\">%s</string>\n"
        "</resources>\n",
        config->app_name);

    fclose(f);
    return 0;
}

int manifest_write_default_icon(const char* drawable_dir) {
    MKDIR(drawable_dir);

    char path[1024];
    snprintf(path, sizeof(path), "%s/ic_launcher.xml", drawable_dir);

    FILE* f = fopen(path, "w");
    if (!f) return -1;

    /* Minimal adaptive icon vector */
    fprintf(f,
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
        "    android:width=\"108dp\"\n"
        "    android:height=\"108dp\"\n"
        "    android:viewportWidth=\"108\"\n"
        "    android:viewportHeight=\"108\">\n"
        "  <path android:fillColor=\"#1976D2\"\n"
        "      android:pathData=\"M0,0h108v108h-108z\" />\n"
        "  <path android:fillColor=\"#FFFFFF\"\n"
        "      android:pathData=\"M34,54 L54,34 L74,54 L54,74Z\" />\n"
        "</vector>\n");

    fclose(f);
    return 0;
}
