/*
 * AndroidManifest.xml Generator
 *
 * Generates a minimal AndroidManifest.xml for a Casperix Native Activity app.
 * The compiled .so is loaded via android.app.NativeActivity which calls
 * android_main() — the entry point generated by the Casperix runtime.
 */

#ifndef MANIFEST_H
#define MANIFEST_H

#include "apk_builder.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Write AndroidManifest.xml to the given file path.
 * Returns 0 on success, -1 on failure. */
int manifest_write(const ApkBuildConfig* config, const char* output_path);

/* Write a minimal strings.xml with just the app_name label */
int manifest_write_strings(const ApkBuildConfig* config, const char* res_dir);

/* Write a minimal drawable/ic_launcher.xml (vector default icon) */
int manifest_write_default_icon(const char* drawable_dir);

#ifdef __cplusplus
}
#endif

#endif /* MANIFEST_H */
