; Generated by Casprix Compiler
; Assemble with: nasm -f win64 (Windows) or nasm -f elf64 (Linux)
bits 64
default rel

extern printf
extern malloc
extern free
extern strcpy
extern setjmp
extern longjmp
extern abort
extern arc_retain
extern arc_release
extern obj_alloc
extern strcat
extern strlen
; ARC memory management
extern arc_alloc_full
extern arc_retain
extern arc_release
; Rc<T> / scope guard (drop planner)
extern rc_release
extern scope_guard_drop_extern

extern ptr_create_i32
extern ptr_free
extern cpx_tokenizer_create
extern cpx_tokenizer_train
extern cpx_tokenizer_encode
extern cpx_tokenizer_decode
extern cpx_tokenizer_save
extern cpx_tokenizer_load
extern cpx_tokenizer_destroy
extern cpx_dataset_create
extern cpx_dataset_save
extern cpx_dataset_load
extern cpx_dataset_destroy
extern cpx_dataset_shuffle
extern cpx_dataset_get_num_sequences
extern cpx_dataset_get_seq_length
extern cpx_dataloader_create
extern cpx_dataloader_next_batch
extern cpx_dataloader_reset
extern cpx_dataloader_destroy
extern cpx_transformer_create
extern cpx_transformer_forward
extern cpx_transformer_save
extern cpx_transformer_load
extern cpx_transformer_destroy
extern cpx_transformer_get_num_params
extern cpx_train_step
extern cpx_eval_step
extern cpx_adam_create
extern cpx_adam_set_lr
extern cpx_adam_destroy
extern cpx_lr_schedule
extern cpx_encode_corpus_to_shards
extern cpx_generate
extern get_time_ms
extern print_f32
extern print_loss_log

section .data
    fmt_int db "%lld", 10, 0
    fmt_float db "%.6f", 10, 0
    fmt_str db "%s", 10, 0
    fmt_true db "True", 10, 0
    fmt_false db "False", 10, 0
    str_0 db "data/tinystories_train.txt", 0
    str_1 db "data/tinystories_val.txt", 0
    str_2 db "data/tok32k.bin", 0
    str_3 db "data/train_shard", 0
    str_4 db "data/val_shard", 0
    str_5 db "checkpoints", 0
    str_6 db "Using tiny test run config (50 steps).", 0
    str_7 db "", 0
    str_8 db "=== Phase 1: BPE Tokenizer Training ===", 0
    str_9 db "Tokenizer training complete.", 0
    str_10 db "=== Phase 2: Tokenizing TinyStories Corpus ===", 0
    str_11 db "Encoding training set...", 0
    str_12 db "Training shards created:", 0
    str_13 db "Encoding validation set...", 0
    str_14 db "Validation shards created:", 0
    str_15 db "Dataset preparation complete.", 0
    str_16 db "=== Phase 3: Model Initialization ===", 0
    str_17 db "Model parameters:", 0
    str_18 db "=== Phase 4: Pre-Training Loop ===", 0
    str_19 db "Total steps:", 0
    str_20 db "Batch size:", 0
    str_21 db "Sequence length:", 0
    str_22 db "--- Validation ---", 0
    str_23 db "  Val loss:", 0
    str_24 db "--- Saving checkpoint at step:", 0
    str_25 db "checkpoints/model_step.bin", 0
    str_26 db "=== Phase 5: Testing Inference (Generation) ===", 0
    str_27 db "Generating from prompt: Once upon a time...", 0
    str_28 db "Once upon a time", 0
    str_29 db "Generation complete (tokens generated).", 0
    str_30 db "=== Training Complete ===", 0
    str_31 db "Saving final model...", 0
    str_32 db "checkpoints/model_final.bin", 0
    str_33 db "All phases complete.", 0
    str_34 db "Your model is saved in: checkpoints/model_final.bin", 0
    str_35 db "Your tokenizer is saved in: data/tok32k.bin", 0
    str_36 db "======================================================", 0
    str_37 db "  Casprix LLM Pre-Training on TinyStories", 0

; VTable for Tokenizer
__vtable_Tokenizer:
    dq Tokenizer_train  ; vtable[0]
    dq Tokenizer_encode  ; vtable[1]
    dq Tokenizer_decode  ; vtable[2]
    dq Tokenizer_save  ; vtable[3]
    dq Tokenizer_destroy  ; vtable[4]

; VTable for Dataset
__vtable_Dataset:
    dq Dataset_shuffle  ; vtable[0]
    dq Dataset_destroy  ; vtable[1]

; VTable for DataLoader
__vtable_DataLoader:
    dq DataLoader_next_batch  ; vtable[0]
    dq DataLoader_reset  ; vtable[1]
    dq DataLoader_destroy  ; vtable[2]

; VTable for Transformer
__vtable_Transformer:
    dq Transformer_get_num_params  ; vtable[0]
    dq Transformer_train_step  ; vtable[1]
    dq Transformer_eval_step  ; vtable[2]
    dq Transformer_generate  ; vtable[3]
    dq Transformer_save  ; vtable[4]
    dq Transformer_destroy  ; vtable[5]

; VTable for Optimizer
__vtable_Optimizer:
    dq Optimizer_set_lr  ; vtable[0]
    dq Optimizer_destroy  ; vtable[1]

; VTable for TrainingConfig
__vtable_TrainingConfig:
    dq TrainingConfig_make_tiny_run  ; vtable[0]

section .bss
    this_ptr resq 1
    cpx_current_exception resq 1  ; current thrown exception object
    cpx_jmp_buf_ptr       resq 1  ; pointer to active setjmp buffer
    __var_vocab_size resq 1
    __var_path resq 1
    __var_tok resq 1
    __var_text resq 1
    __var_len_ptr resq 1
    __var_tokens resq 1
    __var_len resq 1
    __var_num_seqs resq 1
    __var_seq_len resq 1
    __var_vocab resq 1
    __var_ds resq 1
    __var_batch_size resq 1
    __var_shuffle resq 1
    __var_s resq 1
    __var_batch_out resq 1
    __var_targets_out resq 1
    __var_v resq 1
    __var_h resq 1
    __var_l resq 1
    __var_heads resq 1
    __var_ffn resq 1
    __var_seq resq 1
    __var_model resq 1
    __var_opt resq 1
    __var_targets resq 1
    __var_b resq 1
    __var_prompt resq 1
    __var_prompt_len resq 1
    __var_max_tokens resq 1
    __var_temp resq 1
    __var_out_len_ptr resq 1
    __var_result resq 1
    __var_params resq 1
    __var_lr resq 1
    __var_b1 resq 1
    __var_b2 resq 1
    __var_step resq 1
    __var_warmup resq 1
    __var_max_steps resq 1
    __var_max_lr resq 1
    __var_min_lr resq 1
    __var_tok_path resq 1
    __var_in_txt resq 1
    __var_out_prefix resq 1
    __var_size resq 1
    __var_cfg resq 1
    __var_shard_size resq 1
    __var_train_shards resq 1
    __var_val_shards resq 1
    __var_num_params resq 1
    __var_train_ds resq 1
    __var_val_ds resq 1
    __var_train_loader resq 1
    __var_val_loader resq 1
    __var_val_loss_sum resq 1
    __var_tokens_ptr resq 1
    __var_targets_ptr resq 1
    __var_loss resq 1
    __var_avg_val_loss resq 1
    __var_t0 resq 1
    __var_t1 resq 1
    __var_dt resq 1
    __var_prompt_tokens resq 1
    __var_gen_out resq 1

section .text
global main

main:
    push rbp
    mov rbp, rsp

    ; Initialize static fields

    sub rsp, 16
    call __casprix_main
    add rsp, 16
    mov rax, 0
    leave
    ret


; Class: Tokenizer
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

Tokenizer_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    mov rdi, [rbp - 8]
    call cpx_tokenizer_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

__static_Tokenizer_load:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rbp - 8], rdi
    ; Allocate ARC-managed object: New Tokenizer
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_Tokenizer]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_Tokenizer]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 24], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rsi, 0
    mov rdi, [rbp - 24]  ; Load object pointer (this)
    call Tokenizer_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 16], rax
    sub rsp, 0
    mov rdi, [rbp - 8]
    call cpx_tokenizer_load
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rbp - 16]
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rbp - 16]
    push rax  ; save return value across drops
    ; --- scope drops (2 vars) ---
    ; drop 'tok' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_0
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_0:
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_1
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_1:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (1 vars) ---
    ; drop 'tok' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_2
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_2:
    ; --- end scope drops ---
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_3
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_3:
    ; --- end scope drops ---
    leave
    ret

Tokenizer_train:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    call cpx_tokenizer_train
    add rsp, 0
    mov rax, rax
    ; --- scope drops (1 vars) ---
    ; drop 'text' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_4
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_4:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret

Tokenizer_encode:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    call ptr_create_i32
    add rsp, 0
    mov rax, rax
    mov [rbp - 16], rax
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    call cpx_tokenizer_encode
    add rsp, 0
    mov rax, rax
    mov [rbp - 24], rax
    sub rsp, 0
    mov rdi, [rbp - 16]
    call ptr_free
    add rsp, 0
    mov rax, rax
    mov rax, [rbp - 24]
    push rax  ; save return value across drops
    ; --- scope drops (1 vars) ---
    ; drop 'text' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_5
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_5:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (1 vars) ---
    ; drop 'text' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_6
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_6:
    ; --- end scope drops ---
    leave
    ret

Tokenizer_decode:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    call cpx_tokenizer_decode
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

Tokenizer_save:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    call cpx_tokenizer_save
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_7
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_7:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_8
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_8:
    ; --- end scope drops ---
    leave
    ret

Tokenizer_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_tokenizer_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for Tokenizer (releases ref-counted fields)
__dtor_Tokenizer:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

; Class: Dataset
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

Dataset_new:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    mov [rbp - 24], rcx
    sub rsp, 0
    mov rdi, [rbp - 8]
    mov rsi, [rbp - 16]
    mov rdx, [rbp - 24]
    call cpx_dataset_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

__static_Dataset_load:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rbp - 8], rdi
    ; Allocate ARC-managed object: New Dataset
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_Dataset]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_Dataset]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 24], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rsi, 0
    mov rdx, 0
    mov rcx, 0
    mov rdi, [rbp - 24]  ; Load object pointer (this)
    call Dataset_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 16], rax
    sub rsp, 0
    mov rdi, [rbp - 8]
    call cpx_dataset_load
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rbp - 16]
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rbp - 16]
    push rax  ; save return value across drops
    ; --- scope drops (2 vars) ---
    ; drop 'ds' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_9
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_9:
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_10
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_10:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (1 vars) ---
    ; drop 'ds' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_11
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_11:
    ; --- end scope drops ---
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_12
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_12:
    ; --- end scope drops ---
    leave
    ret

Dataset_shuffle:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_dataset_shuffle
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

Dataset_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_dataset_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for Dataset (releases ref-counted fields)
__dtor_Dataset:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

; Class: DataLoader
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

DataLoader_new:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    mov [rbp - 24], rcx
    mov rax, 0
    mov [rbp - 32], rax
    mov rax, [rbp - 24]
    test rax, rax
    jz L14
    mov rax, 1
    mov [rbp - 32], rax
L14:
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 16]
    mov rdx, [rbp - 32]
    call cpx_dataloader_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    ; --- scope drops (1 vars) ---
    ; drop 'ds' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_15
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_15:
    ; --- end scope drops ---
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

DataLoader_next_batch:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    call cpx_dataloader_next_batch
    add rsp, 0
    mov rax, rax
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    cmp rax, rbx
    sete al
    movzx rax, al
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

DataLoader_reset:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_dataloader_reset
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

DataLoader_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_dataloader_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for DataLoader (releases ref-counted fields)
__dtor_DataLoader:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

; Class: Transformer
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

Transformer_new:
    push rbp
    mov rbp, rsp
    sub rsp, 48  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    mov [rbp - 24], rcx
    mov [rbp - 32], r8
    mov [rbp - 40], r9
    mov rax, [rbp + 16]
    mov [rbp - 48], rax
    sub rsp, 0
    mov rdi, [rbp - 8]
    mov rsi, [rbp - 16]
    mov rdx, [rbp - 24]
    mov rcx, [rbp - 32]
    mov r8, [rbp - 40]
    mov r9, [rbp - 48]
    call cpx_transformer_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

__static_Transformer_load:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rbp - 8], rdi
    ; Allocate ARC-managed object: New Transformer
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_Transformer]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_Transformer]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 24], rax  ; save new object ptr
    sub rsp, 16  ; Shadow space + stack args
    mov rsi, 0
    mov rdx, 0
    mov rcx, 0
    mov r8, 0
    mov r9, 0
    mov rax, 0
    mov [rsp + 0], rax  ; Arg 5 on stack
    mov rdi, [rbp - 24]  ; Load object pointer (this)
    call Transformer_new
    add rsp, 16  ; Clean up stack
    mov [rbp - 16], rax
    sub rsp, 0
    mov rdi, [rbp - 8]
    call cpx_transformer_load
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rbp - 16]
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rbp - 16]
    push rax  ; save return value across drops
    ; --- scope drops (2 vars) ---
    ; drop 'model' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_16
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_16:
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_17
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_17:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (1 vars) ---
    ; drop 'model' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_18
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_18:
    ; --- end scope drops ---
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_19
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_19:
    ; --- end scope drops ---
    leave
    ret

Transformer_get_num_params:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_transformer_get_num_params
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

Transformer_train_step:
    push rbp
    mov rbp, rsp
    sub rsp, 48  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    mov [rbp - 24], rcx
    mov [rbp - 32], r8
    mov [rbp - 40], r9
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    mov rcx, [rbp - 24]
    mov r8, [rbp - 32]
    mov r9, [rbp - 40]
    call cpx_train_step
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

Transformer_eval_step:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    mov [rbp - 24], rcx
    mov [rbp - 32], r8
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    mov rcx, [rbp - 24]
    mov r8, [rbp - 32]
    call cpx_eval_step
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

Transformer_generate:
    push rbp
    mov rbp, rsp
    sub rsp, 48  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    mov [rbp - 16], rdx
    mov [rbp - 24], rcx
    movq [rbp - 32], xmm4
    sub rsp, 0
    call ptr_create_i32
    add rsp, 0
    mov rax, rax
    mov [rbp - 40], rax
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    mov rdx, [rbp - 16]
    mov rcx, [rbp - 24]
    mov r8, [rbp - 32]
    mov r9, [rbp - 40]
    movq xmm4, r8
    call cpx_generate
    add rsp, 0
    mov rax, rax
    mov [rbp - 48], rax
    sub rsp, 0
    mov rdi, [rbp - 40]
    call ptr_free
    add rsp, 0
    mov rax, rax
    mov rax, [rbp - 48]
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

Transformer_save:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    call cpx_transformer_save
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_20
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_20:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (1 vars) ---
    ; drop 'path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_21
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_21:
    ; --- end scope drops ---
    leave
    ret

Transformer_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_transformer_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for Transformer (releases ref-counted fields)
__dtor_Transformer:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

; Class: Optimizer
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

Optimizer_new:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    movq [rbp - 16], xmm2
    movq [rbp - 24], xmm3
    movq [rbp - 32], xmm4
    sub rsp, 0
    mov rdi, [rbp - 8]
    mov rsi, [rbp - 16]
    mov rdx, [rbp - 24]
    mov rcx, [rbp - 32]
    movq xmm1, rsi
    movq xmm2, rdx
    movq xmm3, rcx
    call cpx_adam_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

Optimizer_set_lr:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    movq [rbp - 8], xmm1
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    movq xmm1, rsi
    call cpx_adam_set_lr
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

Optimizer_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_adam_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for Optimizer (releases ref-counted fields)
__dtor_Optimizer:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

__casprix_compute_lr:
    push rbp
    mov rbp, rsp
    sub rsp, 48  ; local frame
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    movq [rbp - 32], xmm3
    movq [rbp - 40], xmm4
    sub rsp, 0
    mov rdi, [rbp - 8]
    mov rsi, [rbp - 16]
    mov rdx, [rbp - 24]
    mov rcx, [rbp - 32]
    mov r8, [rbp - 40]
    movq xmm3, rcx
    movq xmm4, r8
    call cpx_lr_schedule
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

__casprix_encode_to_shards:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov [rbp - 32], rcx
    sub rsp, 0
    mov rdi, [rbp - 8]
    mov rsi, [rbp - 16]
    mov rdx, [rbp - 24]
    mov rcx, [rbp - 32]
    call cpx_encode_corpus_to_shards
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    ; --- scope drops (3 vars) ---
    ; drop 'out_prefix' (kind=1)
    mov rdi, [rbp - 24]
    test rdi, rdi
    jz .drop_skip_22
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_22:
    ; drop 'in_txt' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_23
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_23:
    ; drop 'tok_path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_24
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_24:
    ; --- end scope drops ---
    pop rax   ; restore return value
    leave
    ret
    ; --- scope drops (3 vars) ---
    ; drop 'out_prefix' (kind=1)
    mov rdi, [rbp - 24]
    test rdi, rdi
    jz .drop_skip_25
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_25:
    ; drop 'in_txt' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_26
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_26:
    ; drop 'tok_path' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_27
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_27:
    ; --- end scope drops ---
    leave
    ret

; Class: TrainingConfig
; Instance size: 192 bytes
; Fields: 23
;   train_data_prefix: string (offset 8)
;   val_data_prefix: string (offset 16)
;   raw_train_text: string (offset 24)
;   raw_val_text: string (offset 32)
;   tokenizer_path: string (offset 40)
;   checkpoint_dir: string (offset 48)
;   base_vocab_size: i32 (offset 56)
;   target_vocab_size: i32 (offset 64)
;   batch_size: i32 (offset 72)
;   seq_len: i32 (offset 80)
;   max_lr: f32 (offset 88)
;   min_lr: f32 (offset 96)
;   warmup_steps: i32 (offset 104)
;   total_steps: i32 (offset 112)
;   beta1: f32 (offset 120)
;   beta2: f32 (offset 128)
;   epsilon: f32 (offset 136)
;   weight_decay: f32 (offset 144)
;   grad_clip: f32 (offset 152)
;   log_interval: i32 (offset 160)
;   val_interval: i32 (offset 168)
;   val_steps: i32 (offset 176)
;   save_interval: i32 (offset 184)

TrainingConfig_new:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    lea rax, [rel str_0]
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 24], rax  ; Assign to field raw_train_text
    lea rax, [rel str_1]
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 32], rax  ; Assign to field raw_val_text
    lea rax, [rel str_2]
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 40], rax  ; Assign to field tokenizer_path
    lea rax, [rel str_3]
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field train_data_prefix
    lea rax, [rel str_4]
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 16], rax  ; Assign to field val_data_prefix
    lea rax, [rel str_5]
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 48], rax  ; Assign to field checkpoint_dir
    mov rax, 256
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 56], rax  ; Assign to field base_vocab_size
    mov rax, 32000
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 64], rax  ; Assign to field target_vocab_size
    mov rax, 64
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 72], rax  ; Assign to field batch_size
    mov rax, 256
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 80], rax  ; Assign to field seq_len
    mov rax, 0x3F33A92A30553261  ; float 0.0003
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 88], rax  ; Assign to field max_lr
    mov rax, 0x3EFF75104D551D69  ; float 3e-05
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 96], rax  ; Assign to field min_lr
    mov rax, 100
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 104], rax  ; Assign to field warmup_steps
    mov rax, 1050
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 112], rax  ; Assign to field total_steps
    mov rax, 0x3FECCCCCCCCCCCCD  ; float 0.9
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 120], rax  ; Assign to field beta1
    mov rax, 0x3FEE666666666666  ; float 0.95
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 128], rax  ; Assign to field beta2
    mov rax, 0x3E45798EE2308C3A  ; float 1e-08
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 136], rax  ; Assign to field epsilon
    mov rax, 0x3FB999999999999A  ; float 0.1
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 144], rax  ; Assign to field weight_decay
    mov rax, 0x3FF0000000000000  ; float 1
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 152], rax  ; Assign to field grad_clip
    mov rax, 50
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 160], rax  ; Assign to field log_interval
    mov rax, 250
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 168], rax  ; Assign to field val_interval
    mov rax, 20
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 176], rax  ; Assign to field val_steps
    mov rax, 500
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 184], rax  ; Assign to field save_interval
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

TrainingConfig_make_tiny_run:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    mov rax, 50
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 112], rax  ; Assign to field total_steps
    mov rax, 5
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 176], rax  ; Assign to field val_steps
    mov rax, 5
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 160], rax  ; Assign to field log_interval
    mov rax, 25
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 168], rax  ; Assign to field val_interval
    mov rax, 50
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 184], rax  ; Assign to field save_interval
    mov rax, 4
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 72], rax  ; Assign to field batch_size
    mov rax, 64
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 80], rax  ; Assign to field seq_len
    sub rsp, 16
    lea rax, [rel str_6]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    mov rax, 0
    leave
    ret

; Destructor for TrainingConfig (releases ref-counted fields)
__dtor_TrainingConfig:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    ; Release field 'train_data_prefix' at offset 8
    push rdi  ; Save object ptr
    mov rdi, [rdi + 8]  ; Load field ref
    test rdi, rdi  ; Check for NULL
    jz .dtor_TrainingConfig_skip_0
    sub rsp, 16
    call arc_release
    add rsp, 16
.dtor_TrainingConfig_skip_0:
    pop rdi  ; Restore object ptr
    ; Release field 'val_data_prefix' at offset 16
    push rdi  ; Save object ptr
    mov rdi, [rdi + 16]  ; Load field ref
    test rdi, rdi  ; Check for NULL
    jz .dtor_TrainingConfig_skip_1
    sub rsp, 16
    call arc_release
    add rsp, 16
.dtor_TrainingConfig_skip_1:
    pop rdi  ; Restore object ptr
    ; Release field 'raw_train_text' at offset 24
    push rdi  ; Save object ptr
    mov rdi, [rdi + 24]  ; Load field ref
    test rdi, rdi  ; Check for NULL
    jz .dtor_TrainingConfig_skip_2
    sub rsp, 16
    call arc_release
    add rsp, 16
.dtor_TrainingConfig_skip_2:
    pop rdi  ; Restore object ptr
    ; Release field 'raw_val_text' at offset 32
    push rdi  ; Save object ptr
    mov rdi, [rdi + 32]  ; Load field ref
    test rdi, rdi  ; Check for NULL
    jz .dtor_TrainingConfig_skip_3
    sub rsp, 16
    call arc_release
    add rsp, 16
.dtor_TrainingConfig_skip_3:
    pop rdi  ; Restore object ptr
    ; Release field 'tokenizer_path' at offset 40
    push rdi  ; Save object ptr
    mov rdi, [rdi + 40]  ; Load field ref
    test rdi, rdi  ; Check for NULL
    jz .dtor_TrainingConfig_skip_4
    sub rsp, 16
    call arc_release
    add rsp, 16
.dtor_TrainingConfig_skip_4:
    pop rdi  ; Restore object ptr
    ; Release field 'checkpoint_dir' at offset 48
    push rdi  ; Save object ptr
    mov rdi, [rdi + 48]  ; Load field ref
    test rdi, rdi  ; Check for NULL
    jz .dtor_TrainingConfig_skip_5
    sub rsp, 16
    call arc_release
    add rsp, 16
.dtor_TrainingConfig_skip_5:
    pop rdi  ; Restore object ptr
    pop rbp
    ret

__casprix_train_tokenizer:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rbp - 8], rdi
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_8]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Allocate ARC-managed object: New Tokenizer
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_Tokenizer]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_Tokenizer]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 24], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rax, [rbp - 8]
    mov rsi, [rax + 64]  ; Access field target_vocab_size
    mov rdi, [rbp - 24]  ; Load object pointer (this)
    call Tokenizer_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 16], rax
    ; Method call: train
    mov rax, [rbp - 16]
    mov [rbp - 32], rax  ; save object ptr
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rsi, [rax + 24]  ; Access field raw_train_text
    mov rax, [rbp - 8]
    mov rdx, [rax + 64]  ; Access field target_vocab_size
    mov rdi, [rbp - 32]  ; Load object pointer (this)
    ; Virtual method call: train (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: save
    mov rax, [rbp - 16]
    mov [rbp - 32], rax  ; save object ptr
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rsi, [rax + 40]  ; Access field tokenizer_path
    mov rdi, [rbp - 32]  ; Load object pointer (this)
    ; Virtual method call: save (vtable index 3)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 24]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: destroy
    mov rax, [rbp - 16]
    mov [rbp - 32], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 32]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 4)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 32]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    sub rsp, 16
    lea rax, [rel str_9]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; --- scope drops (1 vars) ---
    ; drop 'tok' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_28
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_28:
    ; --- end scope drops ---
    ; --- scope drops (1 vars) ---
    ; drop 'cfg' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_29
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_29:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret

__casprix_prepare_dataset:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rbp - 8], rdi
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_10]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    mov rax, 10000000
    mov [rbp - 16], rax
    sub rsp, 16
    lea rax, [rel str_11]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rdi, [rax + 40]  ; Access field tokenizer_path
    mov rax, [rbp - 8]
    mov rsi, [rax + 24]  ; Access field raw_train_text
    mov rax, [rbp - 8]
    mov rdx, [rax + 8]  ; Access field train_data_prefix
    mov rcx, [rbp - 16]
    call __casprix_encode_to_shards
    add rsp, 0
    mov rax, rax
    mov [rbp - 24], rax
    sub rsp, 16
    lea rax, [rel str_12]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 24]
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_13]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rdi, [rax + 40]  ; Access field tokenizer_path
    mov rax, [rbp - 8]
    mov rsi, [rax + 32]  ; Access field raw_val_text
    mov rax, [rbp - 8]
    mov rdx, [rax + 16]  ; Access field val_data_prefix
    mov rcx, [rbp - 16]
    call __casprix_encode_to_shards
    add rsp, 0
    mov rax, rax
    mov [rbp - 32], rax
    sub rsp, 16
    lea rax, [rel str_14]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 32]
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_15]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; --- scope drops (1 vars) ---
    ; drop 'cfg' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_30
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_30:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret

__casprix_pretrain:
    push rbp
    mov rbp, rsp
    sub rsp, 176  ; local frame
    mov [rbp - 8], rdi
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_16]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Allocate ARC-managed object: New Transformer
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_Transformer]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_Transformer]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 184], rax  ; save new object ptr
    sub rsp, 16  ; Shadow space + stack args
    mov rax, [rbp - 8]
    mov rsi, [rax + 64]  ; Access field target_vocab_size
    mov rdx, 128
    mov rcx, 4
    mov r8, 4
    mov r9, 512
    mov rax, [rbp - 8]
    mov rax, [rax + 80]  ; Access field seq_len
    mov [rsp + 0], rax  ; Arg 5 on stack
    mov rdi, [rbp - 184]  ; Load object pointer (this)
    call Transformer_new
    add rsp, 16  ; Clean up stack
    mov [rbp - 16], rax
    ; Method call: get_num_params
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: get_num_params (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov [rbp - 24], rax
    sub rsp, 16
    lea rax, [rel str_17]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 24]
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Allocate ARC-managed object: New Optimizer
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_Optimizer]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_Optimizer]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 184], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rsi, [rbp - 24]
    mov rax, [rbp - 8]
    mov rdx, [rax + 88]  ; Access field max_lr
    mov rax, [rbp - 8]
    mov rcx, [rax + 120]  ; Access field beta1
    mov rax, [rbp - 8]
    mov r8, [rax + 128]  ; Access field beta2
    mov rdi, [rbp - 184]  ; Load object pointer (this)
    movq xmm2, rdx  ; float ctor arg 1
    movq xmm3, rcx  ; float ctor arg 2
    movq xmm4, r8  ; float ctor arg 3
    call Optimizer_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 32], rax
    ; Static method call: Dataset.load
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rdi, [rax + 8]  ; Access field train_data_prefix
    call __static_Dataset_load
    add rsp, 0
    mov rax, rax
    mov [rbp - 40], rax
    ; Static method call: Dataset.load
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rdi, [rax + 16]  ; Access field val_data_prefix
    call __static_Dataset_load
    add rsp, 0
    mov rax, rax
    mov [rbp - 48], rax
    ; Allocate ARC-managed object: New DataLoader
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_DataLoader]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_DataLoader]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 184], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rsi, [rbp - 40]
    mov rax, [rbp - 8]
    mov rdx, [rax + 72]  ; Access field batch_size
    mov rcx, 1
    mov rdi, [rbp - 184]  ; Load object pointer (this)
    call DataLoader_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 56], rax
    ; Allocate ARC-managed object: New DataLoader
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_DataLoader]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_DataLoader]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 184], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rsi, [rbp - 48]
    mov rax, [rbp - 8]
    mov rdx, [rax + 72]  ; Access field batch_size
    mov rcx, 0
    mov rdi, [rbp - 184]  ; Load object pointer (this)
    call DataLoader_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 64], rax
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_18]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_19]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 8]
    mov rax, [rax + 112]  ; Access field total_steps
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_20]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 8]
    mov rax, [rax + 72]  ; Access field batch_size
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_21]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 8]
    mov rax, [rax + 80]  ; Access field seq_len
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    mov rax, 0
    mov [rbp - 72], rax
L31:
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax + 112]  ; Access field total_steps
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setl al
    movzx rax, al
    test rax, rax
    jz L33
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax + 168]  ; Access field val_interval
    mov rbx, rax
    pop rax
    mov rdx, 0
    idiv rbx
    mov rax, rdx
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz L35
    sub rsp, 16
    lea rax, [rel str_22]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Method call: reset
    mov rax, [rbp - 64]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: reset (vtable index 1)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 8]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov rax, 0x0  ; float 0
    mov [rbp - 80], rax
    mov rax, 0
    mov [rbp - 88], rax
L36:
    mov rax, [rbp - 88]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax + 176]  ; Access field val_steps
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setl al
    movzx rax, al
    test rax, rax
    jz L38
    sub rsp, 0
    call ptr_create_i32
    add rsp, 0
    mov rax, rax
    mov [rbp - 96], rax
    sub rsp, 0
    call ptr_create_i32
    add rsp, 0
    mov rax, rax
    mov [rbp - 104], rax
    ; Method call: next_batch
    mov rax, [rbp - 64]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rsi, [rbp - 96]
    mov rdx, [rbp - 104]
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: next_batch (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: eval_step
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rsi, [rbp - 96]
    mov rdx, [rbp - 104]
    mov rax, [rbp - 8]
    mov rcx, [rax + 72]  ; Access field batch_size
    mov rax, [rbp - 8]
    mov r8, [rax + 80]  ; Access field seq_len
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: eval_step (vtable index 2)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 16]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov [rbp - 112], rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 112]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 80], rax
    sub rsp, 0
    mov rdi, [rbp - 96]
    call ptr_free
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    mov rdi, [rbp - 104]
    call ptr_free
    add rsp, 0
    mov rax, rax
L37:
    mov rax, [rbp - 88]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 88], rax
    jmp L36
L38:
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax + 176]  ; Access field val_steps
    mov rbx, rax
    pop rax
    mov rdx, 0
    idiv rbx
    mov rax, rax
    mov [rbp - 120], rax
    sub rsp, 16
    lea rax, [rel str_23]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 0
    mov rdi, [rbp - 120]
    movq xmm0, rdi
    call print_f32
    add rsp, 0
    mov rax, rax
L35:
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax + 184]  ; Access field save_interval
    mov rbx, rax
    pop rax
    mov rdx, 0
    idiv rbx
    mov rax, rdx
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    cmp rax, rbx
    sete al
    movzx rax, al
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setg al
    movzx rax, al
    mov rbx, rax
    pop rax
    and rax, rbx
    test rax, rax
    jz L40
    sub rsp, 16
    lea rax, [rel str_24]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 72]
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Method call: save
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    lea rsi, [rel str_25]
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: save (vtable index 4)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 32]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
L40:
    sub rsp, 0
    call get_time_ms
    add rsp, 0
    mov rax, rax
    mov [rbp - 128], rax
    sub rsp, 0
    mov rdi, [rbp - 72]
    mov rax, [rbp - 8]
    mov rsi, [rax + 104]  ; Access field warmup_steps
    mov rax, [rbp - 8]
    mov rdx, [rax + 112]  ; Access field total_steps
    mov rax, [rbp - 8]
    mov rcx, [rax + 88]  ; Access field max_lr
    mov rax, [rbp - 8]
    mov r8, [rax + 96]  ; Access field min_lr
    movq xmm3, rcx
    movq xmm4, r8
    call __casprix_compute_lr
    add rsp, 0
    mov rax, rax
    mov [rbp - 136], rax
    ; Method call: set_lr
    mov rax, [rbp - 32]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rsi, [rbp - 136]
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    movq xmm1, rsi  ; float method arg 0
    ; Virtual method call: set_lr (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    sub rsp, 0
    call ptr_create_i32
    add rsp, 0
    mov rax, rax
    mov [rbp - 96], rax
    sub rsp, 0
    call ptr_create_i32
    add rsp, 0
    mov rax, rax
    mov [rbp - 104], rax
    ; Method call: next_batch
    mov rax, [rbp - 56]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rsi, [rbp - 96]
    mov rdx, [rbp - 104]
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: next_batch (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: train_step
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rax, [rbp - 32]
    mov rsi, [rax + 8]  ; Access field handle
    mov rdx, [rbp - 96]
    mov rcx, [rbp - 104]
    mov rax, [rbp - 8]
    mov r8, [rax + 72]  ; Access field batch_size
    mov rax, [rbp - 8]
    mov r9, [rax + 80]  ; Access field seq_len
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: train_step (vtable index 1)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 8]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov [rbp - 112], rax
    sub rsp, 0
    mov rdi, [rbp - 96]
    call ptr_free
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    mov rdi, [rbp - 104]
    call ptr_free
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    call get_time_ms
    add rsp, 0
    mov rax, rax
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    push rax
    mov rax, [rbp - 128]
    mov rbx, rax
    pop rax
    sub rax, rbx
    mov [rbp - 152], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax + 160]  ; Access field log_interval
    mov rbx, rax
    pop rax
    mov rdx, 0
    idiv rbx
    mov rax, rdx
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz L42
    sub rsp, 0
    mov rdi, [rbp - 72]
    mov rsi, [rbp - 112]
    mov rdx, [rbp - 136]
    mov rcx, [rbp - 152]
    movq xmm1, rsi
    movq xmm2, rdx
    call print_loss_log
    add rsp, 0
    mov rax, rax
L42:
L32:
    mov rax, [rbp - 72]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 72], rax
    jmp L31
L33:
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_26]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_27]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Static method call: Tokenizer.load
    sub rsp, 0
    mov rax, [rbp - 8]
    mov rdi, [rax + 40]  ; Access field tokenizer_path
    call __static_Tokenizer_load
    add rsp, 0
    mov rax, rax
    mov [rbp - 160], rax
    ; Method call: encode
    mov rax, [rbp - 160]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    lea rsi, [rel str_28]
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: encode (vtable index 1)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 8]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov [rbp - 168], rax
    ; Method call: generate
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rsi, [rbp - 168]
    mov rdx, 4
    mov rcx, 20
    mov r8, 0x3FF0000000000000  ; float 1
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    movq xmm4, r8  ; float method arg 3
    ; Virtual method call: generate (vtable index 3)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 24]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov [rbp - 176], rax
    sub rsp, 16
    lea rax, [rel str_29]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_30]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_31]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Method call: save
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    lea rsi, [rel str_32]
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: save (vtable index 4)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 32]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: destroy
    mov rax, [rbp - 56]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 2)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 16]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: destroy
    mov rax, [rbp - 64]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 2)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 16]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: destroy
    mov rax, [rbp - 32]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 1)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 8]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: destroy
    mov rax, [rbp - 16]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 5)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 40]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; Method call: destroy
    mov rax, [rbp - 160]
    mov [rbp - 192], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 192]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 4)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 32]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    sub rsp, 16
    lea rax, [rel str_33]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_34]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_35]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; --- scope drops (7 vars) ---
    ; drop 'tok' (kind=1)
    mov rdi, [rbp - 160]
    test rdi, rdi
    jz .drop_skip_43
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_43:
    ; drop 'val_loader' (kind=1)
    mov rdi, [rbp - 64]
    test rdi, rdi
    jz .drop_skip_44
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_44:
    ; drop 'train_loader' (kind=1)
    mov rdi, [rbp - 56]
    test rdi, rdi
    jz .drop_skip_45
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_45:
    ; drop 'val_ds' (kind=1)
    mov rdi, [rbp - 48]
    test rdi, rdi
    jz .drop_skip_46
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_46:
    ; drop 'train_ds' (kind=1)
    mov rdi, [rbp - 40]
    test rdi, rdi
    jz .drop_skip_47
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_47:
    ; drop 'opt' (kind=1)
    mov rdi, [rbp - 32]
    test rdi, rdi
    jz .drop_skip_48
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_48:
    ; drop 'model' (kind=1)
    mov rdi, [rbp - 16]
    test rdi, rdi
    jz .drop_skip_49
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_49:
    ; --- end scope drops ---
    ; --- scope drops (1 vars) ---
    ; drop 'cfg' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_50
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_50:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret

__casprix_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    sub rsp, 16
    lea rax, [rel str_36]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_37]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_36]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Allocate ARC-managed object: New TrainingConfig
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 192  ; Object size
    lea rsi, [__dtor_TrainingConfig]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_TrainingConfig]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 16], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rdi, [rbp - 16]  ; Load object pointer (this)
    call TrainingConfig_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 8], rax
    ; Method call: make_tiny_run
    mov rax, [rbp - 8]
    mov [rbp - 24], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 24]  ; Load object pointer (this)
    ; Virtual method call: make_tiny_run (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    sub rsp, 0
    mov rdi, [rbp - 8]
    call __casprix_train_tokenizer
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    mov rdi, [rbp - 8]
    call __casprix_prepare_dataset
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    mov rdi, [rbp - 8]
    call __casprix_pretrain
    add rsp, 0
    mov rax, rax
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_33]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_34]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_35]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; --- scope drops (1 vars) ---
    ; drop 'cfg' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_51
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_51:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret
