; Generated by Casprix Compiler
; Assemble with: nasm -f win64 (Windows) or nasm -f elf64 (Linux)
bits 64
default rel

extern printf
extern malloc
extern free
extern strcpy
extern setjmp
extern longjmp
extern abort
extern arc_retain
extern arc_release
extern obj_alloc
extern strcat
extern strlen
; ARC memory management
extern arc_alloc_full
extern arc_retain
extern arc_release
; Rc<T> / scope guard (drop planner)
extern rc_release
extern scope_guard_drop_extern

extern cpx_atomic_int_create
extern cpx_atomic_int_destroy
extern cpx_atomic_int_add
extern cpx_atomic_int_load
extern cpx_atomic_int_store
extern cpx_mutex_create
extern cpx_mutex_destroy
extern cpx_mutex_lock
extern cpx_mutex_unlock
extern simulation_storage_init
extern simulation_create
extern simulation_get
extern simulation_update
extern http_server_create
extern http_server_route
extern http_server_listen
extern ptr_create_f32
extern ptr_get_f32
extern ptr_create_buf
extern ptr_to_string

section .data
    fmt_int db "%lld", 10, 0
    fmt_float db "%.6f", 10, 0
    fmt_str db "%s", 10, 0
    fmt_true db "True", 10, 0
    fmt_false db "False", 10, 0
    str_0 db "Request #", 0
    str_1 db "Flight_Sim_01", 0
    str_2 db "Created simulation 101", 0
    str_3 db "Simulation 101 already exists", 0
    str_4 db "Updated simulation 101 (added 5.5)", 0
    str_5 db "Initializing Concurrent Simulation Backend...", 0
    str_6 db "0.0.0.0", 0
    str_7 db "Server listening on port 8080 (Simulated)", 0
    str_8 db "Running atomic race test...", 0
    str_9 db "Final request count:", 0
    str_10 db "Backend simulation successful.", 0

; VTable for AtomicInt
__vtable_AtomicInt:
    dq AtomicInt_add  ; vtable[0]
    dq AtomicInt_load  ; vtable[1]
    dq AtomicInt_store  ; vtable[2]
    dq AtomicInt_destroy  ; vtable[3]

; VTable for Mutex
__vtable_Mutex:
    dq Mutex_lock  ; vtable[0]
    dq Mutex_unlock  ; vtable[1]
    dq Mutex_destroy  ; vtable[2]

section .bss
    this_ptr resq 1
    cpx_current_exception resq 1  ; current thrown exception object
    cpx_jmp_buf_ptr       resq 1  ; pointer to active setjmp buffer
    __var_initial resq 1
    __var_val resq 1
    __var_req resq 1
    __var_userdata resq 1
    __var_counter resq 1
    __var_count resq 1
    __var_id resq 1
    __var_success resq 1
    __var_g_request_count resq 1
    __var_server resq 1
    __var_i resq 1

section .text
global main

main:
    push rbp
    mov rbp, rsp

    ; Initialize static fields

    sub rsp, 16
    call __casprix_main
    add rsp, 16
    mov rax, 0
    leave
    ret


; Class: AtomicInt
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

AtomicInt_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    mov rdi, [rbp - 8]
    call cpx_atomic_int_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

AtomicInt_add:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    call cpx_atomic_int_add
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

AtomicInt_load:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_atomic_int_load
    add rsp, 0
    mov rax, rax
    push rax  ; save return value across drops
    pop rax   ; restore return value
    leave
    ret
    leave
    ret

AtomicInt_store:
    push rbp
    mov rbp, rsp
    sub rsp, 16  ; local frame
    mov [rel this_ptr], rdi
    mov [rbp - 8], rsi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    mov rsi, [rbp - 8]
    call cpx_atomic_int_store
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

AtomicInt_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_atomic_int_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for AtomicInt (releases ref-counted fields)
__dtor_AtomicInt:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

; Class: Mutex
; Instance size: 16 bytes
; Fields: 1
;   handle: rawptr (offset 8)

Mutex_new:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    call cpx_mutex_create
    add rsp, 0
    mov rax, rax
    push rax  ; Save value to assign
    mov rbx, [rel this_ptr]  ; Load 'this' pointer
    pop rax  ; Restore value
    mov [rbx + 8], rax  ; Assign to field handle
    mov rax, [rel this_ptr]  ; Return 'this' from constructor
    leave
    ret

Mutex_lock:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_mutex_lock
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

Mutex_unlock:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_mutex_unlock
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

Mutex_destroy:
    push rbp
    mov rbp, rsp
    mov [rel this_ptr], rdi
    sub rsp, 0
    mov rax, [rel this_ptr]  ; Load 'this' pointer
    mov rdi, [rax + 8]  ; Access field handle
    call cpx_mutex_destroy
    add rsp, 0
    mov rax, rax
    mov rax, 0
    leave
    ret

; Destructor for Mutex (releases ref-counted fields)
__dtor_Mutex:
    push rbp
    mov rbp, rsp
    ; rcx = pointer to object user data
    pop rbp
    ret

__casprix_handle_root:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    ; Method call: add
    mov rax, [rbp - 24]
    mov [rbp - 40], rax  ; save object ptr
    sub rsp, 0
    mov rsi, 1
    mov rdi, [rbp - 40]  ; Load object pointer (this)
    ; Virtual method call: add (vtable index 0)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 0]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    mov [rbp - 32], rax
    sub rsp, 16
    lea rax, [rel str_0]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    mov rax, [rbp - 32]
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    ; --- scope drops (1 vars) ---
    ; drop 'counter' (kind=1)
    mov rdi, [rbp - 24]
    test rdi, rdi
    jz .drop_skip_0
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_0:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret

__casprix_handle_create_sim:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, 101
    mov [rbp - 24], rax
    sub rsp, 0
    mov rdi, [rbp - 24]
    lea rsi, [rel str_1]
    mov rdx, 0x4059000000000000  ; float 100
    movq xmm2, rdx
    call simulation_create
    add rsp, 0
    mov rax, rax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    test rax, rax
    jz L1
    sub rsp, 16
    lea rax, [rel str_2]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    jmp L2
L1:
    sub rsp, 16
    lea rax, [rel str_3]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
L2:
    mov rax, 0
    leave
    ret

__casprix_handle_update_sim:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, 101
    mov [rbp - 24], rax
    sub rsp, 0
    mov rdi, [rbp - 24]
    mov rsi, 0x4016000000000000  ; float 5.5
    movq xmm1, rsi
    call simulation_update
    add rsp, 0
    mov rax, rax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    test rax, rax
    jz L4
    sub rsp, 16
    lea rax, [rel str_4]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
L4:
    mov rax, 0
    leave
    ret

__casprix_main:
    push rbp
    mov rbp, rsp
    sub rsp, 32  ; local frame
    sub rsp, 16
    lea rax, [rel str_5]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 0
    call simulation_storage_init
    add rsp, 0
    mov rax, rax
    ; Allocate ARC-managed object: New AtomicInt
    sub rsp, 16  ; Shadow space/alignment
    mov rdi, 16  ; Object size
    lea rsi, [__dtor_AtomicInt]  ; Destructor
    xor rdx, rdx  ; Scanner (NULL for now)
    call arc_alloc_full
    add rsp, 16
    lea rdx, [__vtable_AtomicInt]  ; Load vtable address
    mov [rax], rdx  ; Set vtable pointer
    mov [rbp - 32], rax  ; save new object ptr
    sub rsp, 0  ; Shadow space + stack args
    mov rsi, 0
    mov rdi, [rbp - 32]  ; Load object pointer (this)
    call AtomicInt_new
    add rsp, 0  ; Clean up stack
    mov [rbp - 8], rax
    sub rsp, 0
    lea rdi, [rel str_6]
    mov rsi, 8080
    call http_server_create
    add rsp, 0
    mov rax, rax
    mov [rbp - 16], rax
    sub rsp, 16
    lea rax, [rel str_7]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_8]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    mov rax, 0
    mov [rbp - 24], rax
L5:
    mov rax, [rbp - 24]
    push rax
    mov rax, 5
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setl al
    movzx rax, al
    test rax, rax
    jz L7
    sub rsp, 0
    mov rdi, 0
    mov rsi, 0
    call __casprix_handle_create_sim
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    mov rdi, 0
    mov rsi, 0
    call __casprix_handle_update_sim
    add rsp, 0
    mov rax, rax
    sub rsp, 0
    mov rdi, 0
    mov rsi, 0
    mov rdx, [rbp - 8]
    call __casprix_handle_root
    add rsp, 0
    mov rax, rax
L6:
    mov rax, [rbp - 24]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 24], rax
    jmp L5
L7:
    sub rsp, 16
    lea rax, [rel str_9]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    ; Method call: load
    mov rax, [rbp - 8]
    mov [rbp - 40], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 40]  ; Load object pointer (this)
    ; Virtual method call: load (vtable index 1)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 8]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    lea rdi, [rel fmt_int]
    mov rsi, rax
    call printf
    add rsp, 16
    sub rsp, 16
    lea rax, [rel str_10]
    lea rdi, [rel fmt_str]
    mov rsi, rax
    call printf
    add rsp, 16
    ; Method call: destroy
    mov rax, [rbp - 8]
    mov [rbp - 40], rax  ; save object ptr
    sub rsp, 0
    mov rdi, [rbp - 40]  ; Load object pointer (this)
    ; Virtual method call: destroy (vtable index 3)
    mov rbx, [rdi]  ; Load vtable pointer from object
    call [rbx + 24]  ; Indirect call through vtable
    add rsp, 0  ; Clean up stack
    ; --- scope drops (1 vars) ---
    ; drop 'g_request_count' (kind=1)
    mov rdi, [rbp - 8]
    test rdi, rdi
    jz .drop_skip_8
    sub rsp, 16
    call arc_release
    add rsp, 16
.drop_skip_8:
    ; --- end scope drops ---
    mov rax, 0
    leave
    ret
